[project]
name = "idico-sales"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.12.5",
    "jaydebeapi>=1.2.3",
    "mcp[cli]>=1.16.0",
    "pandas>=2.3.3",
]
